### ISSUE TITLE
Media Pipe Hands Demo broken on mobile (Android/Chrome)?

### ISSUE THREAD

**Issue by FriskyBishop** [MIDIBlocks/handsfree#97]
Mediapipe facemesh, pose, and holistic (including the hand tracking) demos on handsfree.js.org are working on my devices (android/chrome) however the hands demo and "scroll this page with hands" demo always fails with the following error:

```
hands_solution_wasm_bin.js:9 Uncaught (in promise) RuntimeError: abort(undefined) at Error
    at jsStackTrace (https://handsfree.js.org/handsfree/@mediapipe/hands/node_modules/@mediapipe/hands/hands_solution_wasm_bin.js:9:67549)
    at stackTrace (https://handsfree.js.org/handsfree/@mediapipe/hands/node_modules/@mediapipe/hands/hands_solution_wasm_bin.js:9:67725)
    at abort (https://handsfree.js.org/handsfree/@mediapipe/hands/node_modules/@mediapipe/hands/hands_solution_wasm_bin.js:9:41039)
    at _abort (https://handsfree.js.org/handsfree/@mediapipe/hands/node_modules/@mediapipe/hands/hands_solution_wasm_bin.js:9:179943)
    at https://handsfree.js.org/handsfree/@mediapipe/hands/node_modules/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[10471]:0x49a300
    at https://handsfree.js.org/handsfree/@mediapipe/hands/node_modules/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[10466]:0x49a278
    at https://handsfree.js.org/handsfree/@mediapipe/hands/node_modules/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[10461]:0x499da0
    at https://handsfree.js.org/handsfree/@mediapipe/hands/node_modules/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[10458]:0x499a2a
    at https://handsfree.js.org/handsfree/@mediapipe/hands/node_modules/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[10474]:0x49a359
    at https://handsfree.js.org/handsfree/@mediapipe/hands/node_modules/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[515]:0xebe1
    at abort (https://handsfree.js.org/handsfree/@mediapipe/hands/node_modules/@mediapipe/hands/hands_solution_wasm_bin.js:9:41070)
    at _abort (https://handsfree.js.org/handsfree/@mediapipe/hands/node_modules/@mediapipe/hands/hands_solution_wasm_bin.js:9:179943)
    at https://handsfree.js.org/handsfree/@mediapipe/hands/node_modules/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[10471]:0x49a300
    at https://handsfree.js.org/handsfree/@mediapipe/hands/node_modules/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[10466]:0x49a278
    at https://handsfree.js.org/handsfree/@mediapipe/hands/node_modules/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[10461]:0x499da0
    at https://handsfree.js.org/handsfree/@mediapipe/hands/node_modules/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[10458]:0x499a2a
    at https://handsfree.js.org/handsfree/@mediapipe/hands/node_modules/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[10474]:0x49a359
    at https://handsfree.js.org/handsfree/@mediapipe/hands/node_modules/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[515]:0xebe1
    at https://handsfree.js.org/handsfree/@mediapipe/hands/node_modules/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[502]:0xd956
    at SolutionWasm$send [as send] (eval at new_ (https://handsfree.js.org/handsfree/@mediapipe/hands/node_modules/@mediapipe/hands/hands_solution_wasm_bin.js:9:160446), <anonymous>:9:1)
abort @ hands_solution_wasm_bin.js:9
_abort @ hands_solution_wasm_bin.js:9
(anonymous) @ hands_solution_wasm_bin.wasm:0x49a300
(anonymous) @ hands_solution_wasm_bin.wasm:0x49a278
(anonymous) @ hands_solution_wasm_bin.wasm:0x499da0
(anonymous) @ hands_solution_wasm_bin.wasm:0x499a2a
(anonymous) @ hands_solution_wasm_bin.wasm:0x49a359
(anonymous) @ hands_solution_wasm_bin.wasm:0xebe1
(anonymous) @ hands_solution_wasm_bin.wasm:0xd956
SolutionWasm$send @ VM56:9
(anonymous) @ hands.js:33
Q @ hands.js:10
next @ hands.js:11
k @ hands.js:22
Promise.then (async)
value @ 78.4aceda7b.js:1
(anonymous) @ 78.4aceda7b.js:1
debug.stream.debug.isGettingStream.navigator.mediaDevices.getUserMedia.then.t.debug.$video.onloadedmetadata @ 78.4aceda7b.js:1
```

**Comment by MIDIBlocks** [comment]
Hi thanks for raising this issue! I haven't tested on mobile much yet so it's good to get feedback on this, however I'm afraid it may be an issue with MediaPipe that I won't be able to fix on my own. I did some quick research and it looks like someone recently reported the same issue to MediaPipe which is a little reassuring: https://github.com/google/mediapipe/issues/1459

I've subscribed to that issue and am in their Google Groups list so I'll report back here as soon as I learn anything. Thanks again!
